;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        matlab-electric-comment
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-exdent-or-delete
        mouse-buffer-menu
        mouse-set-region
        ))
