(source gnu)
(source melpa)
(source marmalade)

;; Setup
(depends-on "init-loader")

(depends-on "anzu")
(depends-on "expand-region")
(depends-on "highlight-symbol")
(depends-on "multiple-cursors")
(depends-on "wgrep")
(depends-on "exec-path-from-shell")
(depends-on "ag")
(depends-on "wgrep")
(depends-on "wgrep-ag")
(depends-on "undo-tree")
(depends-on "magit")
(depends-on "dash")
(depends-on "popup")

;; Appearance
(depends-on "color-theme")
;;(depends-on "color-theme-tango")
(depends-on "monokai-theme")
(depends-on "zenburn-theme")
(depends-on "atom-one-dark-theme")
(depends-on "molokai-theme")

;; Config
(depends-on "yasnippet")
(depends-on "flycheck")
(depends-on "redo+")

;; Keybind
(depends-on "smartrep")

;; auto-complete
(depends-on "auto-complete")

;; prog modes
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "json-mode")
(depends-on "yaml-mode")
(depends-on "web-mode")
(depends-on "scss-mode")
(depends-on "markdown-mode")
;; Ruby
(depends-on "ruby-electric")
(depends-on "ruby-block")
(depends-on "rhtml-mode")

;; Rails
(depends-on "rinari")
(depends-on "slim-mode")
(depends-on "rspec-mode")

;; JavaScript
(depends-on "js2-mode")


;; PHP
(depends-on "php-mode")

;; matlab
(depends-on "matlab-mode")
